### ISSUE TITLE
Question: How are the amouts of files measured

### ISSUE THREAD

**Issue by merlinuwe** [technerium/obsidian-vault-size-history#3] opened 2024-08-04 07:29 UTC
This is my vault:

![image](https://github.com/user-attachments/assets/231ba3c4-c539-4216-96d2-1673f1609f74)

When windows counts the marked files, it gets 3955.

![image](https://github.com/user-attachments/assets/8464545d-6da4-4925-af0d-81e85665631d)

How are the files counted in your plugin? Which files and folders are in-/excluded?

![image](https://github.com/user-attachments/assets/74012e20-3680-4472-9618-fc81f39fa918)

**Comment by wizentex** [comment] 2024-08-04 16:29
The plugin uses Obsidian to list all files within the Vault. In your case looks like Obsidian returns the list of 9'529 files.

Let me test on a Windows machine and get back to you.

**Comment by wizentex** [comment] 2024-08-04 19:57
Thank you for using the plugin and reporting the identified issues. I am working on reproducing the issue on Windows.

The plugin does **not** count files in hidden folders, i.e., the ones whose names start with a dot (.sik, .trash, etc.). In your case, it will only count files in the root of the Vault and in the folders you selected: BZZ, IT Grundlagen, Meta, Privat. Therefore, it is unclear why there is a discrepancy between this number and what Windows Explorer returns.

I've added a CSV report file generation feature in the plugin settings. The generated report contains a list of all files counted by the plugin and their creation dates.

Could you please update to version 1.0.5 and run the report from the plugin settings? Maybe you will be able to quickly identify if there are unexpected files in the list. If the report contains 9,529 files and all of them are under the folders from your screenshot (BZZ, IT Grundlagen, Meta, Privat), then something is going on with how Windows calculated the number.

**Comment by merlinuwe** [comment] 2024-08-05 21:53
Thank you very much for implementing this. I count 3740 files -1 for '"File Path", "Created Date"'. 

For me, It seems to be very complex to count files correctly, so I tried some of them. Here you see my result. The green marked field are those I ~ trust, because other tools have nearly the same results.

My problem is one amount in your chart, the "other".

![image](https://github.com/user-attachments/assets/8ffb56e6-327c-41ac-b155-8d4078f555ab)

**Comment by wizentex** [comment] 2024-08-06 01:10
Just to double-check: the generated CSV file has only 3,740 entries, correct? It seems much closer to the number in Windows Explorer.

The plugin builds the vault history assuming that the vault was created when the first markdown file (note) was created. This date becomes the first date of the graph.

Any other files (non-markdown) created before this date will be counted together. If there was a total of 100 such files, the "other files" line will start at 100.

I plan to improve this logic in some way and, at the very least, to give users the ability to choose what date should be considered the start date.

The present issue makes me think there must be something wrong with that calculation. I will look into it.

**Comment by wizentex** [comment] 2024-11-06 06:53
The issue with file count calculation has been fixed in the latest release 1.1.0

**Closed** 2024-11-06 06:53 UTC
