### ISSUE TITLE
For me, the Button in the ribbon is not visible

### ISSUE THREAD

**Issue by merlinuwe** [technerium/obsidian-vault-size-history#2] opened 2024-08-03 18:54 UTC
Thanks for your great plugin.

I cannot see the text at the top (in the legend).

![image](https://github.com/user-attachments/assets/a8ac220b-c24c-4f46-a775-d9a35c496fa5)

 I changed the theme to default, with no better result.

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Base theme: dark
	Community theme: MagicUser v20.8.0
	Snippets enabled: 49
	Restricted mode: off
	Plugins installed: 176
	Plugins enabled: 77
		1: Set View Mode per Note v1.0.3
		2: Advanced Tables v0.21.0
		3: Android nomedia v0.1.0
		4: Auto Link Title v1.5.4
		5: Beautitab v1.6.1
		6: Better Export PDF v1.8.3
		7: Commander v0.5.1
		8: Colored Tags Wrangler v0.19.3
		9: Copy document as HTML v0.8.1
		10: Creases v0.7.0
		11: Custom Classes v2.6.1
		12: Dictionary v2.22.0
		13: Editing Toolbar v2.4.16
		14: Editor Commands Remap v1.0.2
		15: Editor Syntax Highlight v0.1.3
		16: Enhancing Export v1.10.7
		17: Excel to Markdown Table v0.4.0
		18: Export Image plugin v2.3.10
		19: File Explorer Note Count v1.2.2
		20: Google Calendar v1.10.14
		21: Linter v1.25.0
		22: Local Backup v0.1.7
		23: markdown export v1.0.23
		24: Natural Language Dates v0.6.2
		25: Navigate Cursor History v1.1.0
		26: Number Headings v1.16.0
		27: Omnisearch v1.24.0
		28: Paste image rename v1.6.1
		29: Quick Explorer v0.2.8
		30: Quiet Outline v0.3.36
		31: Recent Files v1.4.1
		32: Settings Management v1.0.5
		33: Sheet Plus v1.3.1
		34: Show Current File Path v0.5.2
		35: Sortable v0.3.1
		36: Status Bar Organizer v2.0.2
		37: Style Settings v1.0.8
		38: Symbols Prettifier v1.2.0
		39: Tag Wrangler v0.6.1
		40: Tasks v7.7.0
		41: Templater v2.4.1
		42: Text Extractor v0.5.2
		43: Todo sort v1.0.0
		44: Translate v1.4.9
		45: Typing Transformer v0.4.0
		46: Vault Changelog v0.1.0
		47: Vault Statistics v0.1.3
		48: Webpage HTML Export v1.8.01
		49: Link Converter v0.1.6
		50: Date Inserter v0.3.4
		51: Dataview v0.5.67
		52: Desmos v0.6.8
		53: Plugins Annotations v1.4.0
		54: Color Palette v2.13.7
		55: Docxer v2.0.1
		56: Supercharged Links v0.12.1
		57: Query Control v0.6.0
		58: Note Toolbar v1.9.12
		59: Refresh Preview v1.3.0
		60: Printsidian v0.1.0
		61: Quick Switcher++ v4.4.0
		62: Shell commands v0.22.0
		63: Hover Editor v0.11.20
		64: Reset Font Size v1.0.2
		65: Share my plugin list v0.3.3
		66: Advanced URI v1.42.0
		67: Find orphaned files and broken links v1.10.0
		68: Dashboard navigator v1.1.1
		69: Multi Properties v1.1.1
		70: Table Generator v1.4.1
		71: Image in Editor v2.2.6
		72: OZ Calendar v0.3.4
		73: Open File by Magic Date v0.1.2
		74: Ordered List Style v0.1.0
		75: Better Order List v1.1.1
		76: Super Duper Audio Recorder v1.0.7
		77: Vault Explorer v1.39.0

**Comment by wizentex** [comment] 2024-08-03 22:51
Thank you for raising the issue.

Confirmed the issue with text being barely visible in the dark mode - working on a fix for that.

Regarding missing ribbon icon: when you open context menu on the ribbon bar (right mouse click on the bar since you are on Windows), do you see the "Vault size history" in the list of items? See example below:

<img width="459" alt="Screenshot 2024-08-03 at 6 47 45 PM" src="https://github.com/user-attachments/assets/895e5d8f-698b-4040-9252-a0d35dcab52c">

**Comment by wizentex** [comment] 2024-08-04 00:14
Release 1.0.4 fixes the issue with text being barely visible in dark mode. Please update.

**Comment by merlinuwe** [comment] 2024-08-04 07:15
The ribbon icon is visible, now.

![image](https://github.com/user-attachments/assets/bf6a62a3-c2b8-4857-a421-de087e8cb9a6)

The readabilty is perfect in dark mode

![image](https://github.com/user-attachments/assets/65e32d9e-2fa6-4128-a47d-ce8d4b29a0f4)

and much better in light mode.

![image](https://github.com/user-attachments/assets/6247b65a-9796-4e5f-938e-7c6e5a359a48)

Thank you very much!

**Comment by wizentex** [comment] 2024-08-04 16:21
Closing as fixed.

**Closed by wizentex** 2024-08-04 16:21 UTC
Labels: bug
